FROM node:20-alpine AS ng-builder
RUN mkdir -p /app
WORKDIR /app
COPY . /app
ENV NODE_OPTIONS=--max_old_space_size=8192
ENV ASPNETCORE_ENVIRONMENT=Local
ENV REMOTE_SERVICE_BASE_URL=""
ENV APP_BASE_URL=""
RUN npm install --legacy-peer-deps
RUN npx ng build --configuration=production --output-hashing=all --output-path /app/dist/publish/ --base-href=/

FROM nginx:alpine
EXPOSE 8080
ENV ASPNETCORE_ENVIRONMENT=Local
ENV REMOTE_SERVICE_BASE_URL=""
ENV APP_BASE_URL=""
COPY --chown=nginx:nginx ./config/nginx.conf /etc/nginx/nginx.conf
COPY --chown=nginx:nginx --from=ng-builder /app/dist/publish /usr/share/nginx/html

RUN chown -R nginx:nginx /var/cache/nginx /var/log/nginx /usr/share/nginx/html

HEALTHCHECK --interval=30s --timeout=10s --start-period=60s --retries=3 CMD wget --no-verbose --tries=1 --spider http://localhost:8080 || exit 1

USER nginx

CMD ["/bin/sh", "-c", "envsubst < /usr/share/nginx/html/assets/env.template.js > /usr/share/nginx/html/assets/env.js && exec nginx -g 'daemon off;'"]
