FROM node:18-alpine AS ng-builder
RUN mkdir -p /app
WORKDIR /app
COPY . /app
ENV NODE_OPTIONS=--max_old_space_size=8192
RUN npm install --force
RUN npx ng build --configuration=production --output-hashing=all --output-path /app/dist/publish/ --base-href=/

FROM nginx
EXPOSE 80
EXPOSE 443
COPY ./config/nginx.conf /etc/nginx/nginx.conf
COPY --from=ng-builder /app/dist/publish /usr/share/nginx/html

CMD ["/bin/sh",  "-c",  "envsubst < /usr/share/nginx/html/assets/env.template.js > /usr/share/nginx/html/assets/env.js && exec nginx -g 'daemon off;'"]