<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <TargetFrameworks>net10.0</TargetFrameworks>
    <RootNamespace>Eaf.EntityFrameworkCore.SampleApp.Tests</RootNamespace>
	<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
	  <IsPackable>false</IsPackable>
  </PropertyGroup>


	<ItemGroup>
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
		<PackageReference Include="Abp.AutoMapper" Version="10.4.0" />
		<PackageReference Include="Abp.ZeroCore" Version="10.4.0" />
		<PackageReference Include="Abp.ZeroCore.EntityFrameworkCore" Version="10.4.0" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.3" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.3">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.3">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Castle.Windsor.MsDependencyInjection" Version="4.1.0" />
	</ItemGroup>


	<ItemGroup>
	  <PackageReference Update="coverlet.collector" Version="8.0.0" />
	  <PackageReference Update="coverlet.msbuild" Version="10.0.1" />
	  <PackageReference Update="xunit.runner.visualstudio" Version="3.1.4" />
	</ItemGroup>
  
</Project>
