<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <RootNamespace>Eaf</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Abp.TestBase" Version="10.4.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="Moq" Version="4.20.72" />
    <PackageReference Include="Shouldly" Version="4.3.0" />
    <PackageReference Include="NSubstitute" Version="5.3.0" />
    <PackageReference Include="xunit" Version="2.9.3" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Update="xunit.runner.visualstudio" Version="3.1.4" />
    <PackageReference Update="coverlet.collector" Version="8.0.0" />
    <PackageReference Update="coverlet.msbuild" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Eaf.Middleware.Application\Eaf.Middleware.Application.csproj" />
    <ProjectReference Include="..\..\src\Eaf.Middleware.Core\Eaf.Middleware.Core.csproj" />
  </ItemGroup>

</Project>
