//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eaf.Renamer.Win
{
    using System;
    using System.ComponentModel;
    using System.Drawing;
    using System.Windows.Forms;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    partial class FormMain
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;


        private Label lbOriginalName;
        private Label lbOriginalProjectName;
        private Label lbProjectPath;
        private TextBox txtOldCompanyName;
        private TextBox txtOldProjectName;
        private Button btnStart;
        private TextBox txtNewProjectName;
        private TextBox txtNewCompanyName;
        private Label lbNewProjectName;
        private Label lbNewCompanyName;
        private Label lbArrow2nd;
        private Label lbArrow1st;
        private Button btnSelect;
        private Button btnClose;
        private ProgressBar progressBar1;
        private Label lbTitle;
        private Panel panel1;
        private Label label9;
        public const int WM_SYSCOMMAND = 274;
        public const int SC_MOVE = 61456;
        public const int HTCAPTION = 2;
        private TextBox Console;
        private PictureBox pictureBoxLogo;
        private Label lbReset;
        private Button btnReset;
        private TextBox txtFilter;
        private TextBox txtRootDir;
        private Label lbOriginalAreaName;
        private TextBox txtOldAreaName;
        private Label lbArrow3rd;
        private Label lbNewAreaName;
        private TextBox txtNewAreaName;
        private CheckBox chk;
        private Button btnChangeLog;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public FormMain()
        {
            InitializeComponent();
            renameTemplate = new Eaf.Renamer.Lib.RenameTemplate();
        }

        private void InitializeComponent()
        {
            this.lbOriginalName = new System.Windows.Forms.Label();
            this.lbOriginalProjectName = new System.Windows.Forms.Label();
            this.lbProjectPath = new System.Windows.Forms.Label();
            this.txtOldCompanyName = new System.Windows.Forms.TextBox();
            this.txtOldProjectName = new System.Windows.Forms.TextBox();
            this.btnStart = new System.Windows.Forms.Button();
            this.txtNewProjectName = new System.Windows.Forms.TextBox();
            this.txtNewCompanyName = new System.Windows.Forms.TextBox();
            this.lbNewProjectName = new System.Windows.Forms.Label();
            this.lbNewCompanyName = new System.Windows.Forms.Label();
            this.lbArrow2nd = new System.Windows.Forms.Label();
            this.lbArrow1st = new System.Windows.Forms.Label();
            this.btnSelect = new System.Windows.Forms.Button();
            this.progressBar1 = new System.Windows.Forms.ProgressBar();
            this.btnClose = new System.Windows.Forms.Button();
            this.lbTitle = new System.Windows.Forms.Label();
            this.panel1 = new System.Windows.Forms.Panel();
            this.btnChangeLog = new System.Windows.Forms.Button();
            this.pictureBoxLogo = new System.Windows.Forms.PictureBox();
            this.label9 = new System.Windows.Forms.Label();
            this.Console = new System.Windows.Forms.TextBox();
            this.lbReset = new System.Windows.Forms.Label();
            this.btnReset = new System.Windows.Forms.Button();
            this.txtFilter = new System.Windows.Forms.TextBox();
            this.txtRootDir = new System.Windows.Forms.TextBox();
            this.lbOriginalAreaName = new System.Windows.Forms.Label();
            this.txtOldAreaName = new System.Windows.Forms.TextBox();
            this.lbArrow3rd = new System.Windows.Forms.Label();
            this.lbNewAreaName = new System.Windows.Forms.Label();
            this.txtNewAreaName = new System.Windows.Forms.TextBox();
            this.chk = new System.Windows.Forms.CheckBox();
            this.panel1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBoxLogo)).BeginInit();
            this.SuspendLayout();
            // 
            // lbOriginalName
            // 
            this.lbOriginalName.AutoSize = true;
            this.lbOriginalName.BackColor = System.Drawing.Color.White;
            this.lbOriginalName.Cursor = System.Windows.Forms.Cursors.Hand;
            this.lbOriginalName.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.lbOriginalName.Location = new System.Drawing.Point(16, 706);
            this.lbOriginalName.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.lbOriginalName.Name = "lbOriginalName";
            this.lbOriginalName.Size = new System.Drawing.Size(114, 16);
            this.lbOriginalName.TabIndex = 0;
            this.lbOriginalName.Text = "Original API name";
            this.lbOriginalName.Click += new System.EventHandler(this.lbOriginalName_Click);
            // 
            // lbOriginalProjectName
            // 
            this.lbOriginalProjectName.AutoSize = true;
            this.lbOriginalProjectName.BackColor = System.Drawing.Color.White;
            this.lbOriginalProjectName.Cursor = System.Windows.Forms.Cursors.Hand;
            this.lbOriginalProjectName.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.lbOriginalProjectName.Location = new System.Drawing.Point(16, 738);
            this.lbOriginalProjectName.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.lbOriginalProjectName.Name = "lbOriginalProjectName";
            this.lbOriginalProjectName.Size = new System.Drawing.Size(106, 16);
            this.lbOriginalProjectName.TabIndex = 1;
            this.lbOriginalProjectName.Text = "Original UI name";
            this.lbOriginalProjectName.Click += new System.EventHandler(this.lbOriginalProjectName_Click);
            // 
            // lbProjectPath
            // 
            this.lbProjectPath.AutoSize = true;
            this.lbProjectPath.BackColor = System.Drawing.Color.White;
            this.lbProjectPath.Cursor = System.Windows.Forms.Cursors.Hand;
            this.lbProjectPath.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.lbProjectPath.Location = new System.Drawing.Point(16, 823);
            this.lbProjectPath.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.lbProjectPath.Name = "lbProjectPath";
            this.lbProjectPath.Size = new System.Drawing.Size(78, 16);
            this.lbProjectPath.TabIndex = 2;
            this.lbProjectPath.Text = "Project path";
            // 
            // txtOldCompanyName
            // 
            this.txtOldCompanyName.BackColor = System.Drawing.Color.White;
            this.txtOldCompanyName.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.txtOldCompanyName.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.txtOldCompanyName.Location = new System.Drawing.Point(184, 704);
            this.txtOldCompanyName.Margin = new System.Windows.Forms.Padding(4);
            this.txtOldCompanyName.Name = "txtOldCompanyName";
            this.txtOldCompanyName.Size = new System.Drawing.Size(298, 22);
            this.txtOldCompanyName.TabIndex = 3;
            this.txtOldCompanyName.Text = "Eaf.ProjectName";
            // 
            // txtOldProjectName
            // 
            this.txtOldProjectName.BackColor = System.Drawing.Color.White;
            this.txtOldProjectName.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.txtOldProjectName.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.txtOldProjectName.Location = new System.Drawing.Point(184, 736);
            this.txtOldProjectName.Margin = new System.Windows.Forms.Padding(4);
            this.txtOldProjectName.Name = "txtOldProjectName";
            this.txtOldProjectName.Size = new System.Drawing.Size(298, 22);
            this.txtOldProjectName.TabIndex = 4;
            this.txtOldProjectName.Text = "eaf-ProjectName-ui";
            // 
            // btnStart
            // 
            this.btnStart.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.btnStart.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(128)))), ((int)(((byte)(0)))));
            this.btnStart.Cursor = System.Windows.Forms.Cursors.Hand;
            this.btnStart.FlatAppearance.BorderSize = 0;
            this.btnStart.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnStart.Font = new System.Drawing.Font("Microsoft Sans Serif", 14.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnStart.ForeColor = System.Drawing.Color.White;
            this.btnStart.Location = new System.Drawing.Point(719, 800);
            this.btnStart.Margin = new System.Windows.Forms.Padding(4);
            this.btnStart.Name = "btnStart";
            this.btnStart.Size = new System.Drawing.Size(259, 59);
            this.btnStart.TabIndex = 6;
            this.btnStart.Text = "Execute";
            this.btnStart.UseVisualStyleBackColor = false;
            this.btnStart.Click += new System.EventHandler(this.BtnStart_Click);
            // 
            // txtNewProjectName
            // 
            this.txtNewProjectName.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.txtNewProjectName.BackColor = System.Drawing.Color.White;
            this.txtNewProjectName.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.txtNewProjectName.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.txtNewProjectName.Location = new System.Drawing.Point(679, 736);
            this.txtNewProjectName.Margin = new System.Windows.Forms.Padding(4);
            this.txtNewProjectName.Name = "txtNewProjectName";
            this.txtNewProjectName.Size = new System.Drawing.Size(298, 22);
            this.txtNewProjectName.TabIndex = 11;
            this.txtNewProjectName.Text = "eaf-ProjectName-ui";
            // 
            // txtNewCompanyName
            // 
            this.txtNewCompanyName.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.txtNewCompanyName.BackColor = System.Drawing.Color.White;
            this.txtNewCompanyName.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.txtNewCompanyName.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.txtNewCompanyName.Location = new System.Drawing.Point(679, 704);
            this.txtNewCompanyName.Margin = new System.Windows.Forms.Padding(4);
            this.txtNewCompanyName.Name = "txtNewCompanyName";
            this.txtNewCompanyName.Size = new System.Drawing.Size(298, 22);
            this.txtNewCompanyName.TabIndex = 10;
            this.txtNewCompanyName.Text = "Eaf.ProjectName";
            // 
            // lbNewProjectName
            // 
            this.lbNewProjectName.AutoSize = true;
            this.lbNewProjectName.BackColor = System.Drawing.Color.White;
            this.lbNewProjectName.Cursor = System.Windows.Forms.Cursors.Hand;
            this.lbNewProjectName.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.lbNewProjectName.Location = new System.Drawing.Point(561, 738);
            this.lbNewProjectName.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.lbNewProjectName.Name = "lbNewProjectName";
            this.lbNewProjectName.Size = new System.Drawing.Size(87, 16);
            this.lbNewProjectName.TabIndex = 9;
            this.lbNewProjectName.Text = "New UI name";
            this.lbNewProjectName.Click += new System.EventHandler(this.lbNewProjectName_Click);
            // 
            // lbNewCompanyName
            // 
            this.lbNewCompanyName.AutoSize = true;
            this.lbNewCompanyName.BackColor = System.Drawing.Color.White;
            this.lbNewCompanyName.Cursor = System.Windows.Forms.Cursors.Hand;
            this.lbNewCompanyName.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.lbNewCompanyName.Location = new System.Drawing.Point(561, 706);
            this.lbNewCompanyName.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.lbNewCompanyName.Name = "lbNewCompanyName";
            this.lbNewCompanyName.Size = new System.Drawing.Size(95, 16);
            this.lbNewCompanyName.TabIndex = 8;
            this.lbNewCompanyName.Text = "New API name";
            this.lbNewCompanyName.Click += new System.EventHandler(this.lbNewCompanyName_Click);
            // 
            // lbArrow2nd
            // 
            this.lbArrow2nd.AutoSize = true;
            this.lbArrow2nd.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(173)))), ((int)(((byte)(173)))), ((int)(((byte)(173)))));
            this.lbArrow2nd.Location = new System.Drawing.Point(491, 738);
            this.lbArrow2nd.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.lbArrow2nd.Name = "lbArrow2nd";
            this.lbArrow2nd.Size = new System.Drawing.Size(21, 16);
            this.lbArrow2nd.TabIndex = 12;
            this.lbArrow2nd.Text = "=>";
            // 
            // lbArrow1st
            // 
            this.lbArrow1st.AutoSize = true;
            this.lbArrow1st.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(173)))), ((int)(((byte)(173)))), ((int)(((byte)(173)))));
            this.lbArrow1st.Location = new System.Drawing.Point(491, 706);
            this.lbArrow1st.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.lbArrow1st.Name = "lbArrow1st";
            this.lbArrow1st.Size = new System.Drawing.Size(21, 16);
            this.lbArrow1st.TabIndex = 13;
            this.lbArrow1st.Text = "=>";
            // 
            // btnSelect
            // 
            this.btnSelect.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(77)))), ((int)(((byte)(77)))), ((int)(((byte)(77)))));
            this.btnSelect.BackgroundImageLayout = System.Windows.Forms.ImageLayout.None;
            this.btnSelect.Cursor = System.Windows.Forms.Cursors.Hand;
            this.btnSelect.FlatAppearance.BorderSize = 0;
            this.btnSelect.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnSelect.ForeColor = System.Drawing.Color.White;
            this.btnSelect.Location = new System.Drawing.Point(611, 816);
            this.btnSelect.Margin = new System.Windows.Forms.Padding(4);
            this.btnSelect.Name = "btnSelect";
            this.btnSelect.Size = new System.Drawing.Size(100, 31);
            this.btnSelect.TabIndex = 14;
            this.btnSelect.Text = "Select";
            this.btnSelect.UseVisualStyleBackColor = false;
            this.btnSelect.Click += new System.EventHandler(this.BtnSelect_Click);
            // 
            // progressBar1
            // 
            this.progressBar1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(51)))), ((int)(((byte)(51)))));
            this.progressBar1.Dock = System.Windows.Forms.DockStyle.Bottom;
            this.progressBar1.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(128)))), ((int)(((byte)(0)))));
            this.progressBar1.Location = new System.Drawing.Point(0, 871);
            this.progressBar1.Margin = new System.Windows.Forms.Padding(0);
            this.progressBar1.Name = "progressBar1";
            this.progressBar1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.progressBar1.Size = new System.Drawing.Size(990, 14);
            this.progressBar1.Step = 1;
            this.progressBar1.Style = System.Windows.Forms.ProgressBarStyle.Continuous;
            this.progressBar1.TabIndex = 15;
            this.progressBar1.Visible = false;
            // 
            // btnClose
            // 
            this.btnClose.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom)
            | System.Windows.Forms.AnchorStyles.Right)));
            this.btnClose.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(77)))), ((int)(((byte)(77)))), ((int)(((byte)(77)))));
            this.btnClose.Cursor = System.Windows.Forms.Cursors.Hand;
            this.btnClose.FlatAppearance.BorderSize = 0;
            this.btnClose.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnClose.Font = new System.Drawing.Font("Microsoft Sans Serif", 15.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnClose.ForeColor = System.Drawing.Color.White;
            this.btnClose.Location = new System.Drawing.Point(925, 4);
            this.btnClose.Margin = new System.Windows.Forms.Padding(4);
            this.btnClose.Name = "btnClose";
            this.btnClose.Size = new System.Drawing.Size(60, 37);
            this.btnClose.TabIndex = 16;
            this.btnClose.Text = "X";
            this.btnClose.UseVisualStyleBackColor = false;
            this.btnClose.Click += new System.EventHandler(this.BtnClose_Click);
            // 
            // lbTitle
            // 
            this.lbTitle.AutoSize = true;
            this.lbTitle.BackColor = System.Drawing.Color.White;
            this.lbTitle.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lbTitle.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.lbTitle.Location = new System.Drawing.Point(179, 8);
            this.lbTitle.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.lbTitle.Name = "lbTitle";
            this.lbTitle.Size = new System.Drawing.Size(211, 25);
            this.lbTitle.TabIndex = 19;
            this.lbTitle.Text = "EAF Solution Renamer";
            // 
            // panel1
            // 
            this.panel1.BackColor = System.Drawing.Color.White;
            this.panel1.Controls.Add(this.btnChangeLog);
            this.panel1.Controls.Add(this.pictureBoxLogo);
            this.panel1.Controls.Add(this.lbTitle);
            this.panel1.Controls.Add(this.btnClose);
            this.panel1.Location = new System.Drawing.Point(0, 0);
            this.panel1.Margin = new System.Windows.Forms.Padding(4);
            this.panel1.Name = "panel1";
            this.panel1.Size = new System.Drawing.Size(985, 42);
            this.panel1.TabIndex = 20;
            // 
            // btnChangeLog
            // 
            this.btnChangeLog.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom)
            | System.Windows.Forms.AnchorStyles.Right)));
            this.btnChangeLog.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(77)))), ((int)(((byte)(77)))), ((int)(((byte)(77)))));
            this.btnChangeLog.BackgroundImageLayout = System.Windows.Forms.ImageLayout.None;
            this.btnChangeLog.Cursor = System.Windows.Forms.Cursors.Hand;
            this.btnChangeLog.FlatAppearance.BorderSize = 0;
            this.btnChangeLog.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnChangeLog.ForeColor = System.Drawing.Color.White;
            this.btnChangeLog.Location = new System.Drawing.Point(769, 4);
            this.btnChangeLog.Margin = new System.Windows.Forms.Padding(4);
            this.btnChangeLog.Name = "btnChangeLog";
            this.btnChangeLog.Size = new System.Drawing.Size(144, 38);
            this.btnChangeLog.TabIndex = 26;
            this.btnChangeLog.Text = "Change Log";
            this.btnChangeLog.UseVisualStyleBackColor = false;
            this.btnChangeLog.Click += new System.EventHandler(this.btnChangeLog_Click);
            // 
            // pictureBoxLogo
            // 
            this.pictureBoxLogo.ErrorImage = global::EAFRenamer.Properties.Resources.eaf72;
            this.pictureBoxLogo.Image = global::EAFRenamer.Properties.Resources.eaf72;
            this.pictureBoxLogo.InitialImage = global::EAFRenamer.Properties.Resources.eaf72;
            this.pictureBoxLogo.Location = new System.Drawing.Point(8, 4);
            this.pictureBoxLogo.Margin = new System.Windows.Forms.Padding(4);
            this.pictureBoxLogo.Name = "pictureBoxLogo";
            this.pictureBoxLogo.Size = new System.Drawing.Size(42, 38);
            this.pictureBoxLogo.SizeMode = System.Windows.Forms.PictureBoxSizeMode.StretchImage;
            this.pictureBoxLogo.TabIndex = 23;
            this.pictureBoxLogo.TabStop = false;
            // 
            // label9
            // 
            this.label9.AutoSize = true;
            this.label9.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(173)))), ((int)(((byte)(173)))), ((int)(((byte)(173)))));
            this.label9.Location = new System.Drawing.Point(469, 220);
            this.label9.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.label9.Name = "label9";
            this.label9.Size = new System.Drawing.Size(21, 16);
            this.label9.TabIndex = 21;
            this.label9.Text = "=>";
            // 
            // Console
            // 
            this.Console.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left)
            | System.Windows.Forms.AnchorStyles.Right)));
            this.Console.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(50)))), ((int)(((byte)(50)))), ((int)(((byte)(50)))));
            this.Console.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.Console.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(218)))), ((int)(((byte)(218)))), ((int)(((byte)(218)))));
            this.Console.ImeMode = System.Windows.Forms.ImeMode.Off;
            this.Console.Location = new System.Drawing.Point(8, 49);
            this.Console.Margin = new System.Windows.Forms.Padding(4);
            this.Console.Multiline = true;
            this.Console.Name = "Console";
            this.Console.ReadOnly = true;
            this.Console.ScrollBars = System.Windows.Forms.ScrollBars.Both;
            this.Console.Size = new System.Drawing.Size(974, 610);
            this.Console.TabIndex = 22;
            // 
            // lbReset
            // 
            this.lbReset.AutoSize = true;
            this.lbReset.BackColor = System.Drawing.Color.White;
            this.lbReset.Cursor = System.Windows.Forms.Cursors.Hand;
            this.lbReset.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.lbReset.Location = new System.Drawing.Point(16, 674);
            this.lbReset.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.lbReset.Name = "lbReset";
            this.lbReset.Size = new System.Drawing.Size(125, 16);
            this.lbReset.TabIndex = 23;
            this.lbReset.Text = "Replace file content";
            // 
            // btnReset
            // 
            this.btnReset.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.btnReset.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(77)))), ((int)(((byte)(77)))), ((int)(((byte)(77)))));
            this.btnReset.BackgroundImageLayout = System.Windows.Forms.ImageLayout.None;
            this.btnReset.Cursor = System.Windows.Forms.Cursors.Hand;
            this.btnReset.FlatAppearance.BorderSize = 0;
            this.btnReset.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnReset.ForeColor = System.Drawing.Color.White;
            this.btnReset.Location = new System.Drawing.Point(869, 667);
            this.btnReset.Margin = new System.Windows.Forms.Padding(4);
            this.btnReset.Name = "btnReset";
            this.btnReset.Size = new System.Drawing.Size(108, 31);
            this.btnReset.TabIndex = 25;
            this.btnReset.Text = "Default";
            this.btnReset.UseVisualStyleBackColor = false;
            this.btnReset.Click += new System.EventHandler(this.BtnReset_Click);
            // 
            // txtFilter
            // 
            this.txtFilter.BackColor = System.Drawing.Color.White;
            this.txtFilter.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.txtFilter.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtFilter.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.txtFilter.Location = new System.Drawing.Point(184, 672);
            this.txtFilter.Margin = new System.Windows.Forms.Padding(4);
            this.txtFilter.Name = "txtFilter";
            this.txtFilter.Size = new System.Drawing.Size(677, 22);
            this.txtFilter.TabIndex = 24;
            this.txtFilter.Text = ".cs,.cshtml,.js,.ts,.csproj,.sln,.xml,.config,.DotSettings,.json,.xaml,.txt,.html" +
    ",.gitignore,.ps1,.md,.plist,.tpl";
            // 
            // txtRootDir
            // 
            this.txtRootDir.BackColor = System.Drawing.Color.White;
            this.txtRootDir.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.txtRootDir.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.txtRootDir.Location = new System.Drawing.Point(109, 821);
            this.txtRootDir.Margin = new System.Windows.Forms.Padding(4);
            this.txtRootDir.Name = "txtRootDir";
            this.txtRootDir.Size = new System.Drawing.Size(493, 22);
            this.txtRootDir.TabIndex = 26;
            // 
            // lbOriginalAreaName
            // 
            this.lbOriginalAreaName.AutoSize = true;
            this.lbOriginalAreaName.BackColor = System.Drawing.Color.White;
            this.lbOriginalAreaName.Cursor = System.Windows.Forms.Cursors.Hand;
            this.lbOriginalAreaName.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.lbOriginalAreaName.Location = new System.Drawing.Point(49, 770);
            this.lbOriginalAreaName.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.lbOriginalAreaName.Name = "lbOriginalAreaName";
            this.lbOriginalAreaName.Size = new System.Drawing.Size(121, 16);
            this.lbOriginalAreaName.TabIndex = 27;
            this.lbOriginalAreaName.Text = "Original area name";
            this.lbOriginalAreaName.Click += new System.EventHandler(this.lbOriginalAreaName_Click);
            // 
            // txtOldAreaName
            // 
            this.txtOldAreaName.BackColor = System.Drawing.Color.White;
            this.txtOldAreaName.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.txtOldAreaName.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.txtOldAreaName.Location = new System.Drawing.Point(184, 768);
            this.txtOldAreaName.Margin = new System.Windows.Forms.Padding(4);
            this.txtOldAreaName.Name = "txtOldAreaName";
            this.txtOldAreaName.Size = new System.Drawing.Size(298, 22);
            this.txtOldAreaName.TabIndex = 28;
            this.txtOldAreaName.Text = "AppAreaName";
            // 
            // lbArrow3rd
            // 
            this.lbArrow3rd.AutoSize = true;
            this.lbArrow3rd.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(173)))), ((int)(((byte)(173)))), ((int)(((byte)(173)))));
            this.lbArrow3rd.Location = new System.Drawing.Point(491, 773);
            this.lbArrow3rd.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.lbArrow3rd.Name = "lbArrow3rd";
            this.lbArrow3rd.Size = new System.Drawing.Size(21, 16);
            this.lbArrow3rd.TabIndex = 29;
            this.lbArrow3rd.Text = "=>";
            // 
            // lbNewAreaName
            // 
            this.lbNewAreaName.AutoSize = true;
            this.lbNewAreaName.BackColor = System.Drawing.Color.White;
            this.lbNewAreaName.Cursor = System.Windows.Forms.Cursors.Hand;
            this.lbNewAreaName.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.lbNewAreaName.Location = new System.Drawing.Point(561, 770);
            this.lbNewAreaName.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.lbNewAreaName.Name = "lbNewAreaName";
            this.lbNewAreaName.Size = new System.Drawing.Size(102, 16);
            this.lbNewAreaName.TabIndex = 30;
            this.lbNewAreaName.Text = "New area name";
            // 
            // txtNewAreaName
            // 
            this.txtNewAreaName.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.txtNewAreaName.BackColor = System.Drawing.Color.White;
            this.txtNewAreaName.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.txtNewAreaName.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.txtNewAreaName.Location = new System.Drawing.Point(679, 768);
            this.txtNewAreaName.Margin = new System.Windows.Forms.Padding(4);
            this.txtNewAreaName.Name = "txtNewAreaName";
            this.txtNewAreaName.Size = new System.Drawing.Size(298, 22);
            this.txtNewAreaName.TabIndex = 31;
            this.txtNewAreaName.Text = "App";
            // 
            // chk
            // 
            this.chk.AutoSize = true;
            this.chk.Checked = true;
            this.chk.CheckState = System.Windows.Forms.CheckState.Checked;
            this.chk.Location = new System.Drawing.Point(21, 770);
            this.chk.Margin = new System.Windows.Forms.Padding(4);
            this.chk.Name = "chk";
            this.chk.Size = new System.Drawing.Size(18, 17);
            this.chk.TabIndex = 32;
            this.chk.UseVisualStyleBackColor = true;
            this.chk.Click += new System.EventHandler(this.chk_CheckedChanged);
            // 
            // FormMain
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(120F, 120F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Dpi;
            this.AutoScroll = true;
            this.BackColor = System.Drawing.Color.White;
            this.ClientSize = new System.Drawing.Size(990, 885);
            this.Controls.Add(this.chk);
            this.Controls.Add(this.txtNewAreaName);
            this.Controls.Add(this.lbNewAreaName);
            this.Controls.Add(this.lbArrow3rd);
            this.Controls.Add(this.txtOldAreaName);
            this.Controls.Add(this.lbOriginalAreaName);
            this.Controls.Add(this.txtRootDir);
            this.Controls.Add(this.btnReset);
            this.Controls.Add(this.txtFilter);
            this.Controls.Add(this.lbReset);
            this.Controls.Add(this.Console);
            this.Controls.Add(this.label9);
            this.Controls.Add(this.progressBar1);
            this.Controls.Add(this.btnSelect);
            this.Controls.Add(this.lbArrow1st);
            this.Controls.Add(this.lbArrow2nd);
            this.Controls.Add(this.txtNewProjectName);
            this.Controls.Add(this.txtNewCompanyName);
            this.Controls.Add(this.lbNewProjectName);
            this.Controls.Add(this.lbNewCompanyName);
            this.Controls.Add(this.btnStart);
            this.Controls.Add(this.txtOldProjectName);
            this.Controls.Add(this.txtOldCompanyName);
            this.Controls.Add(this.lbProjectPath);
            this.Controls.Add(this.lbOriginalProjectName);
            this.Controls.Add(this.lbOriginalName);
            this.Controls.Add(this.panel1);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.ImeMode = System.Windows.Forms.ImeMode.Off;
            this.Margin = new System.Windows.Forms.Padding(4);
            this.MaximizeBox = false;
            this.MinimizeBox = false;
            this.Name = "FormMain";
            this.ShowIcon = false;
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "EAF Solution Renamer";
            this.MouseDown += new System.Windows.Forms.MouseEventHandler(this.Form1_MouseDown);
            this.panel1.ResumeLayout(false);
            this.panel1.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBoxLogo)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EAFRenamer.FormMain", typeof(FormMain).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=17,Y=17}.
        /// </summary>
        internal static System.Drawing.Point backgroundWorker_TrayLocation
        {
            get
            {
                object obj = ResourceManager.GetObject("backgroundWorker.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
    }
}
