<Project Sdk="Microsoft.NET.Sdk">

	<Import Project="..\..\common.props" />

	<PropertyGroup>
		<RootNamespace>Eaf</RootNamespace>
		<TargetFrameworks>net10.0</TargetFrameworks>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<AssemblyName>Eaf.SqlServerCache</AssemblyName>
		<PackageId>Eaf.SqlServerCache</PackageId>
		<PackageTags>asp.net;asp.net mvc;application framework;web framework;framework;domain driven design;Sql Server;Caching;Eaf;Boilerplate;NET9</PackageTags>
		<Description>Enterprise Application Foundation - Sql Server Cache implementation</Description>
		<PackageReadmeFile>README.md</PackageReadmeFile>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Abp" Version="10.4.0" />
		<PackageReference Include="ExtendedXmlSerializer" Version="3.10.0" />
		<PackageReference Include="Microsoft.Extensions.Caching.SqlServer" Version="10.0.8" />
		<PackageReference Include="Microsoft.IdentityModel.JsonWebTokens" Version="8.18.0" />
		<PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.18.0" />
	</ItemGroup>

	<ItemGroup>
		<None Include="README.md" Pack="true" PackagePath="\" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.2" />
		<PackageReference Include="Microsoft.Extensions.Caching.Abstractions" Version="10.0.8" />
		<PackageReference Update="SourceLink.Create.CommandLine" Version="2.8.3" />
	</ItemGroup>
</Project>
