<Project Sdk="Microsoft.NET.Sdk">
	<Import Project="..\..\common.props"></Import>
	<PropertyGroup>
		<RootNamespace>Eaf</RootNamespace>
		<TargetFrameworks>net10.0</TargetFrameworks>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<AssemblyName>Eaf.Notifications.Sms</AssemblyName>
		<PackageId>Eaf.Notifications.Sms</PackageId>
		<PackageTags>asp.net;asp.net mvc;application framework;web framework;framework;domain driven design;multitenancy;sms;notification;Eaf;Boilerplate</PackageTags>
		<Description>Enterprise Application Foundation - Module Notifications - SMS Sender</Description>
		<PackageReadmeFile>README.md</PackageReadmeFile>
	</PropertyGroup>
	<ItemGroup>
		<None Include="README.md" Pack="true" PackagePath="\" />
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="Abp" Version="10.5.0" />
		<PackageReference Include="Microsoft.Extensions.Http" Version="10.0.9" />
	</ItemGroup>
	<ItemGroup>
		<PackageReference Update="SourceLink.Create.CommandLine" Version="2.8.3" />
	</ItemGroup>
</Project>
