<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\common.props" />

  <PropertyGroup>
    <RootNamespace>Eaf</RootNamespace>
    <TargetFrameworks>net10.0</TargetFrameworks>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <AssemblyName>Eaf.DynamicEntityProperties</AssemblyName>
    <PackageId>Eaf.DynamicEntityProperties</PackageId>
    <PackageTags>asp.net;asp.net mvc;application framework;web framework;framework;domain driven design;Eaf;Boilerplate;dynamic;entity;properties</PackageTags>
    <Description>Enterprise Application Foundation - Dynamic Entity Properties integration for ASP.NET Boilerplate</Description>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Abp" Version="10.5.0" />
    <PackageReference Include="Abp.AutoMapper" Version="10.5.0" />
  </ItemGroup>

  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
      <_Parameter1>Eaf.DynamicEntityProperties.Tests</_Parameter1>
    </AssemblyAttribute>
    <None Include="README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

</Project>
